# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    services:
      postgres:
        image: kibaes/postgres-logical-replication-dev:14-dev-20221002
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespw
          POSTGRES_DB: playground
        ports:
          - "5432:5432"

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: node -v
    - run: npm -v
    - run: npm ci
    - run: npm run build
    - name: Test
      run: npm test
      env:
        POSTGRES_PORT: 5432
    - uses: phoenix-actions/test-reporting@v8
      if: success() || failure()
      id: test-report
      with:
        name: JEST Tests (${{ matrix.node-version }})
        path: junit.xml
        reporter: jest-junit
