name: 'Test Report'
on:
  workflow_run:
    workflows: ['Node.js CI']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: false

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: phoenix-actions/test-reporting@v8
        id: test-report
        with:
          artifact: test-results-${{ matrix.node-version }}
          name: JEST Tests
          path: junit.xml
          reporter: jest-junit
